// DO NOT EDIT -- automatically generated by ../gen-opt.pl
// from crash.default.options


// stop being C compatible, to simplify things.  The entire code base 
// is in C++ now, except the kernel drivers.  Can always create a C interface 
// if need be.

#ifndef __crash_OPTIONS_H
#define __crash_OPTIONS_H

extern int __ekm__choice_ioctl;
extern int __ekm__disk_choice_ioctl;
extern int __ekm__extra_kernel_failures;
extern int __ekm__log_ioctl;
extern int __ekm__max_kernel_choicepoints;
extern int __ekm__net;
extern const char* __ekm__net_server;
extern int __ekm__run_ioctl;
extern int __fsck__cache;
extern int __fsck__crash;
extern int __fsck__deterministic_threshold;
extern int __fsck__random_tries;
extern int __permuter__cluster;
extern int __permuter__kernel_writes;
extern const char* __permuter__type;
extern int __rdd__sectors;
extern const char* __recovery_permuter__type;
extern int __simulator__default_time;


#endif

