/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "explode_rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
rpc_systemf_1(char *cmd,  CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, rpc_systemf,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &cmd,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
rpc_unlink_1(char *pathname,  CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, rpc_unlink,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &pathname,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
rpc_rmdir_1(char *pathname,  CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, rpc_rmdir,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &pathname,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
rpc_creat_1(char *pathname, int mode,  CLIENT *clnt)
{
	rpc_creat_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.pathname = pathname;
	arg.mode = mode;
	if (clnt_call (clnt, rpc_creat, (xdrproc_t) xdr_rpc_creat_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
rpc_creat_osync_1(char *pathname, int mode,  CLIENT *clnt)
{
	rpc_creat_osync_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.pathname = pathname;
	arg.mode = mode;
	if (clnt_call (clnt, rpc_creat_osync, (xdrproc_t) xdr_rpc_creat_osync_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
rpc_mkdir_1(char *pathname, int mode,  CLIENT *clnt)
{
	rpc_mkdir_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.pathname = pathname;
	arg.mode = mode;
	if (clnt_call (clnt, rpc_mkdir, (xdrproc_t) xdr_rpc_mkdir_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
rpc_link_1(char *oldpath, char *newpath,  CLIENT *clnt)
{
	rpc_link_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.oldpath = oldpath;
	arg.newpath = newpath;
	if (clnt_call (clnt, rpc_link, (xdrproc_t) xdr_rpc_link_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
rpc_symlink_1(char *oldpath, char *newpath,  CLIENT *clnt)
{
	rpc_symlink_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.oldpath = oldpath;
	arg.newpath = newpath;
	if (clnt_call (clnt, rpc_symlink, (xdrproc_t) xdr_rpc_symlink_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
rpc_rename_1(char *oldpath, char *newpath,  CLIENT *clnt)
{
	rpc_rename_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.oldpath = oldpath;
	arg.newpath = newpath;
	if (clnt_call (clnt, rpc_rename, (xdrproc_t) xdr_rpc_rename_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
rpc_truncate_1(char *pathname, int length,  CLIENT *clnt)
{
	rpc_truncate_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.pathname = pathname;
	arg.length = length;
	if (clnt_call (clnt, rpc_truncate, (xdrproc_t) xdr_rpc_truncate_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
rpc_open_1(char *pathname, int flags,  CLIENT *clnt)
{
	rpc_open_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.pathname = pathname;
	arg.flags = flags;
	if (clnt_call (clnt, rpc_open, (xdrproc_t) xdr_rpc_open_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

read_res *
rpc_read_1(int fd, int count,  CLIENT *clnt)
{
	rpc_read_1_argument arg;
	static read_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.fd = fd;
	arg.count = count;
	if (clnt_call (clnt, rpc_read, (xdrproc_t) xdr_rpc_read_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_read_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
rpc_write_1(int fd, buffer buf, int count,  CLIENT *clnt)
{
	rpc_write_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.fd = fd;
	arg.buf = buf;
	arg.count = count;
	if (clnt_call (clnt, rpc_write, (xdrproc_t) xdr_rpc_write_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
rpc_close_1(int fd,  CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, rpc_close,
		(xdrproc_t) xdr_int, (caddr_t) &fd,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
rpc_fsync_1(int fd,  CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, rpc_fsync,
		(xdrproc_t) xdr_int, (caddr_t) &fd,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
rpc_ftruncate_1(int fd, int length,  CLIENT *clnt)
{
	rpc_ftruncate_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.fd = fd;
	arg.length = length;
	if (clnt_call (clnt, rpc_ftruncate, (xdrproc_t) xdr_rpc_ftruncate_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
rpc_pwrite_1(int fd, buffer buf, int count, int offset,  CLIENT *clnt)
{
	rpc_pwrite_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.fd = fd;
	arg.buf = buf;
	arg.count = count;
	arg.offset = offset;
	if (clnt_call (clnt, rpc_pwrite, (xdrproc_t) xdr_rpc_pwrite_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
rpc_sync_1(CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	 if (clnt_call (clnt, rpc_sync, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

stat_res *
rpc_stat_1(char *pathname,  CLIENT *clnt)
{
	static stat_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, rpc_stat,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &pathname,
		(xdrproc_t) xdr_stat_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

abstract_path_res *
rpc_abstract_path_1(char *pathname,  CLIENT *clnt)
{
	static abstract_path_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, rpc_abstract_path,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &pathname,
		(xdrproc_t) xdr_abstract_path_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
