/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "explode_rpc.h"

bool_t
xdr_abstract_path_res (XDR *xdrs, abstract_path_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errornum))
		 return FALSE;
	switch (objp->errornum) {
	case 0:
		 if (!xdr_array (xdrs, (char **)&objp->abstract_path_res_u.fs_buf.fs_buf_val, (u_int *) &objp->abstract_path_res_u.fs_buf.fs_buf_len, ~0,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_buffer (XDR *xdrs, buffer *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->buffer_val, (u_int *) &objp->buffer_len, 2048,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read_res (XDR *xdrs, read_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errornum))
		 return FALSE;
	switch (objp->errornum) {
	case 0:
		 if (!xdr_buffer (xdrs, &objp->read_res_u.buf))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_stat_res (XDR *xdrs, stat_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errornum))
		 return FALSE;
	switch (objp->errornum) {
	case 0:
		 if (!xdr_opaque (xdrs, objp->stat_res_u.buf, 96))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_rpc_creat_1_argument (XDR *xdrs, rpc_creat_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->pathname, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_creat_osync_1_argument (XDR *xdrs, rpc_creat_osync_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->pathname, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_mkdir_1_argument (XDR *xdrs, rpc_mkdir_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->pathname, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_link_1_argument (XDR *xdrs, rpc_link_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->oldpath, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->newpath, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_symlink_1_argument (XDR *xdrs, rpc_symlink_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->oldpath, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->newpath, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_rename_1_argument (XDR *xdrs, rpc_rename_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->oldpath, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->newpath, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_truncate_1_argument (XDR *xdrs, rpc_truncate_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->pathname, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->length))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_open_1_argument (XDR *xdrs, rpc_open_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->pathname, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_read_1_argument (XDR *xdrs, rpc_read_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_write_1_argument (XDR *xdrs, rpc_write_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_buffer (xdrs, &objp->buf))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_ftruncate_1_argument (XDR *xdrs, rpc_ftruncate_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->length))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_pwrite_1_argument (XDR *xdrs, rpc_pwrite_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_buffer (xdrs, &objp->buf))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	return TRUE;
}
