// DO NOT EDIT -- automatically generated by ../gen-opt.pl
// from mcl.default.options


// stop being C compatible, to simplify things.  The entire code base 
// is in C++ now, except the kernel drivers.  Can always create a C interface 
// if need be.

#ifndef __mcl_OPTIONS_H
#define __mcl_OPTIONS_H

extern const char* __mcl__ckpt_file;
extern int __mcl__ckpt_states;
extern int __mcl__clear_on_bug_exit;
extern int __mcl__max_bugs;
extern int __mcl__max_state;
extern int __mcl__persistent;
extern int __mcl__random_seed;
extern int __mcl__reboot_crashes;
extern int __mcl__simulation;
extern int __mcl__simulation_length;
extern const char* __mcl__state_queue;
extern const char* __mcl__trace_dir;
extern int __mcl__verbose;
extern const char* __monitor__addr;
extern int __monitor__port;
extern int __monitor__timeout;
extern int __monitor__use_vm;
extern const char* __monitor__vm_path;


#endif

