/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "explode_rpc.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static int *
_rpc_systemf_1 (char * *argp, struct svc_req *rqstp)
{
	return (rpc_systemf_1_svc(*argp, rqstp));
}

static int *
_rpc_unlink_1 (char * *argp, struct svc_req *rqstp)
{
	return (rpc_unlink_1_svc(*argp, rqstp));
}

static int *
_rpc_rmdir_1 (char * *argp, struct svc_req *rqstp)
{
	return (rpc_rmdir_1_svc(*argp, rqstp));
}

static int *
_rpc_creat_1 (rpc_creat_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_creat_1_svc(argp->pathname, argp->mode, rqstp));
}

static int *
_rpc_creat_osync_1 (rpc_creat_osync_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_creat_osync_1_svc(argp->pathname, argp->mode, rqstp));
}

static int *
_rpc_mkdir_1 (rpc_mkdir_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_mkdir_1_svc(argp->pathname, argp->mode, rqstp));
}

static int *
_rpc_link_1 (rpc_link_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_link_1_svc(argp->oldpath, argp->newpath, rqstp));
}

static int *
_rpc_symlink_1 (rpc_symlink_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_symlink_1_svc(argp->oldpath, argp->newpath, rqstp));
}

static int *
_rpc_rename_1 (rpc_rename_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_rename_1_svc(argp->oldpath, argp->newpath, rqstp));
}

static int *
_rpc_truncate_1 (rpc_truncate_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_truncate_1_svc(argp->pathname, argp->length, rqstp));
}

static int *
_rpc_open_1 (rpc_open_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_open_1_svc(argp->pathname, argp->flags, rqstp));
}

static read_res *
_rpc_read_1 (rpc_read_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_read_1_svc(argp->fd, argp->count, rqstp));
}

static int *
_rpc_write_1 (rpc_write_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_write_1_svc(argp->fd, argp->buf, argp->count, rqstp));
}

static int *
_rpc_close_1 (int  *argp, struct svc_req *rqstp)
{
	return (rpc_close_1_svc(*argp, rqstp));
}

static int *
_rpc_fsync_1 (int  *argp, struct svc_req *rqstp)
{
	return (rpc_fsync_1_svc(*argp, rqstp));
}

static int *
_rpc_ftruncate_1 (rpc_ftruncate_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_ftruncate_1_svc(argp->fd, argp->length, rqstp));
}

static int *
_rpc_pwrite_1 (rpc_pwrite_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_pwrite_1_svc(argp->fd, argp->buf, argp->count, argp->offset, rqstp));
}

static int *
_rpc_sync_1 (void  *argp, struct svc_req *rqstp)
{
	return (rpc_sync_1_svc(rqstp));
}

static stat_res *
_rpc_stat_1 (char * *argp, struct svc_req *rqstp)
{
	return (rpc_stat_1_svc(*argp, rqstp));
}

static abstract_path_res *
_rpc_abstract_path_1 (char * *argp, struct svc_req *rqstp)
{
	return (rpc_abstract_path_1_svc(*argp, rqstp));
}

static void
explodeprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *rpc_systemf_1_arg;
		char *rpc_unlink_1_arg;
		char *rpc_rmdir_1_arg;
		rpc_creat_1_argument rpc_creat_1_arg;
		rpc_creat_osync_1_argument rpc_creat_osync_1_arg;
		rpc_mkdir_1_argument rpc_mkdir_1_arg;
		rpc_link_1_argument rpc_link_1_arg;
		rpc_symlink_1_argument rpc_symlink_1_arg;
		rpc_rename_1_argument rpc_rename_1_arg;
		rpc_truncate_1_argument rpc_truncate_1_arg;
		rpc_open_1_argument rpc_open_1_arg;
		rpc_read_1_argument rpc_read_1_arg;
		rpc_write_1_argument rpc_write_1_arg;
		int rpc_close_1_arg;
		int rpc_fsync_1_arg;
		rpc_ftruncate_1_argument rpc_ftruncate_1_arg;
		rpc_pwrite_1_argument rpc_pwrite_1_arg;
		char *rpc_stat_1_arg;
		char *rpc_abstract_path_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case rpc_systemf:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_systemf_1;
		break;

	case rpc_unlink:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_unlink_1;
		break;

	case rpc_rmdir:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_rmdir_1;
		break;

	case rpc_creat:
		_xdr_argument = (xdrproc_t) xdr_rpc_creat_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_creat_1;
		break;

	case rpc_creat_osync:
		_xdr_argument = (xdrproc_t) xdr_rpc_creat_osync_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_creat_osync_1;
		break;

	case rpc_mkdir:
		_xdr_argument = (xdrproc_t) xdr_rpc_mkdir_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_mkdir_1;
		break;

	case rpc_link:
		_xdr_argument = (xdrproc_t) xdr_rpc_link_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_link_1;
		break;

	case rpc_symlink:
		_xdr_argument = (xdrproc_t) xdr_rpc_symlink_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_symlink_1;
		break;

	case rpc_rename:
		_xdr_argument = (xdrproc_t) xdr_rpc_rename_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_rename_1;
		break;

	case rpc_truncate:
		_xdr_argument = (xdrproc_t) xdr_rpc_truncate_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_truncate_1;
		break;

	case rpc_open:
		_xdr_argument = (xdrproc_t) xdr_rpc_open_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_open_1;
		break;

	case rpc_read:
		_xdr_argument = (xdrproc_t) xdr_rpc_read_1_argument;
		_xdr_result = (xdrproc_t) xdr_read_res;
		local = (char *(*)(char *, struct svc_req *)) _rpc_read_1;
		break;

	case rpc_write:
		_xdr_argument = (xdrproc_t) xdr_rpc_write_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_write_1;
		break;

	case rpc_close:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_close_1;
		break;

	case rpc_fsync:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_fsync_1;
		break;

	case rpc_ftruncate:
		_xdr_argument = (xdrproc_t) xdr_rpc_ftruncate_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_ftruncate_1;
		break;

	case rpc_pwrite:
		_xdr_argument = (xdrproc_t) xdr_rpc_pwrite_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_pwrite_1;
		break;

	case rpc_sync:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _rpc_sync_1;
		break;

	case rpc_stat:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_stat_res;
		local = (char *(*)(char *, struct svc_req *)) _rpc_stat_1;
		break;

	case rpc_abstract_path:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_abstract_path_res;
		local = (char *(*)(char *, struct svc_req *)) _rpc_abstract_path_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (EXPLODEPROG, EXPLODEVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, EXPLODEPROG, EXPLODEVERS, explodeprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (EXPLODEPROG, EXPLODEVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, EXPLODEPROG, EXPLODEVERS, explodeprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (EXPLODEPROG, EXPLODEVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
