
// DO NOT EDIT -- automatically generated by ../gen-opt.pl
// from bdb.default.options

#include <iostream>
#include <fstream>
#include <string>
#include <cstdlib>
#include <assert.h>

#include "options.h"

using namespace std;

int __berkeleydb__commits = 1;

int __berkeleydb__datalen = 8192;

int __berkeleydb__keylen = 4096;

int __berkeleydb__puts = 1;



namespace {

struct _options: public options {

    virtual ~_options() {






    }

    virtual void init() {




    }

    virtual int load(const char *dom, const char *opt, const char *val) {
    if (!strcmp (dom, "berkeleydb")) {
        if (!strcmp (opt, "commits"))
            { __berkeleydb__commits = (int)strtoul(val, 0, 0); return 1; }
        if (!strcmp (opt, "datalen"))
            { __berkeleydb__datalen = (int)strtoul(val, 0, 0); return 1; }
        if (!strcmp (opt, "keylen"))
            { __berkeleydb__keylen = (int)strtoul(val, 0, 0); return 1; }
        if (!strcmp (opt, "puts"))
            { __berkeleydb__puts = (int)strtoul(val, 0, 0); return 1; }

    }

        return 0;
    }
    
    virtual void print(std::ostream &o) {
    o << "berkeleydb::commits    " << __berkeleydb__commits << endl;
    o << "berkeleydb::datalen    " << __berkeleydb__datalen << endl;
    o << "berkeleydb::keylen    " << __berkeleydb__keylen << endl;
    o << "berkeleydb::puts    " << __berkeleydb__puts << endl;        
    }
    
};

struct register_options x(new _options);

}

