// DO NOT EDIT -- automatically generated by ../gen-opt.pl
// from storage.default.options


// stop being C compatible, to simplify things.  The entire code base 
// is in C++ now, except the kernel drivers.  Can always create a C interface 
// if need be.

#ifndef __storage_OPTIONS_H
#define __storage_OPTIONS_H

extern int __fs__blk_size;
extern int __fs__retries_on_failed_umount;
extern const char* __fs__type;
extern int __fsck__mode;
extern int __fsck__verbose;
extern const char* __raid__level;
extern const char* __svn__type;
extern int __vmware__compact;


#endif

